// Brook Azene
// How to use the random function in the standard library header file to test and produce random data.


/*  Many games/simulations need to generate random values to work properly. This is what the rand()
    function does:
    
            rand()
                - Returns a pseudo-random number in the range of 0 to RAND_MAX; RAND_MAX == 32767

                            int rand(void)          >>>     No parameter passed
                            
                - Requires the stdlib.h header file as one of the preprocessor directives
                * If you want to narrow the the random numbers, the % (modulus) operator can be used. This is because this operator gives the integer remainder left over when one number is divided by another  i.e. 20 % 4 = 0 because there is no remainder, but 21 % 4 = 1, 22 % 4 = 2 etc.
                        
                        E.g.
                            
                            dice = (rand() % 5) + 1;    >>> Values 1 through 6   
                        
                        ! This is not a true random value; it has some bias
            
    
    To get a truly RANDOM value, something extra is required.
    
            To seed the random number generator means to give it an initial base value from which the rand() function can offset with a random number.
                ! The srand() function literally means to set the seed for rand(). Once that's done, it's rand() that actually does the generation of new values.
                * srand() needs to be called before the first call to rand() or else srand(1) will be called, setting seed to 1.
                ! The number inside the srand() parantheses must be different every time you run the program because the same set of random values will be produced if the number doesn't change.
                * To get a different number every time the program runs, put the exact time of day in the parantheses. Do this by declaring a time variable, use the 'time_t' declaration (represents the clock time as an integer which is a part of the calendar time) and send its address (using the ampersand character at the front of the variable name) to the srand() function.
                - If a random number generator is not needed and the same set of random values are needed then just using the rand() function is suitable.
                ! The time.h header file must be included before the seeding of the random number generator with the time of the day stored on the device.


    ! DON'T USE INTEGER VARIABLE TO HOLD THE RETURN VALUE FROM THESE MATH FUNCTIONS (UNLESS THE FUNCTION RETURN VALUES ARE TYPECASTED). THIS IS BECAUSE THEY RETURN FLOAT OR DOUBLE VALUES EVEN SOME LIKE CEIL() RETURN INTEGER RESULTS.
*/



// This program uses rand() to roll two dice and present the result. The user is asked to guess whether the next dice roll will be higher or lower or the same as the previous roll. The user has only one chance then the program quits. One way to improve this program is to use a do...while loop on the whole program that will let the it keep running until the user quits.
#include <stdio.h>  // For I/O functions e.g. puts(), printf()....
#include <string.h>
#include <ctype.h>  // For character/case-testing/mapping functions
#include <time.h>   // For use of the time_t data type and time() function


int main() {

    int d1, d2; //  Will hold the values generated by rand() for each roll
    int total1, total2; //  Will hold the sum of each dice roll
    time_t t;   // Internal clock time of device is represented as an integer by this data type (initialised with value)
    char ans;   //  Stores guess input from user

    srand(time(&t));    //  Needed to make sure each random number generated is different

    d1 = (rand() % 5) + 1;  //  rand() returns number 0-5 but die are 1-6 so 1 is added to produce a die value
    d2 = (rand() % 5) + 1;
    total1 = d1 + d2;
    printf("\nFirst roll of the dice was %d and %d, and the total is %d.\n\n", d1, d2, total1);
    
    //  Keeps looping until user input matches one of the three accepted inputs for the loop
    do 
    {
        puts("\nDo you think the next roll will be (H)igher, (L)ower, or the (S)ame?\n");
        puts("Enter H, L, or S as your guess.\n");

        scanf(" %c", &ans); //  Takes input
        ans = toupper(ans); //  Converts to uppercase for ease of verification
    } while ((ans != 'H') && (ans != 'L') && (ans != 'S')); //  If 'ans' is equal to at least one of them, loop ends


    d1 = (rand() % 5) + 1;  //  This is the second roll being generated
    d2 = (rand() % 5) + 1;
    total2 = d1 + d2;
    printf("\nSecond roll of the dice was %d and %d, and the total is %d.\n\n", d1, d2, total2);


    //  The if statements below will verify whether the generated numbers being compared match with the guess the user inputted before the second dice roll.
    if (ans == 'L')
    {
        if ( total2 < total1) 
        {
            printf("\nGood job! You were right! %d is lower than %d.\n", total2, total1);
        }
        else 
        {
            printf("\nSorry! %d is not lower than %d\n.", total2, total1);
        }
    }
    else if (ans == 'H') 
    {
                if ( total2 > total1) 
        {
            printf("\nGood job! You were right! %d is higher than %d.\n", total2, total1);
        }
        else 
        {
            printf("\nSorry! %d is not higher than %d\n.", total2, total1);
        }
    }
    else if (ans == 'S')
    {
        if ( total2 == total1) 
        {
            printf("\nGood job! You were right! %d is the same as %d.\n", total2, total1);
        }
        else 
        {
            printf("\nSorry! %d is not the same as %d\n.", total2, total1);
        }
    }

    return 0;
}